-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 18-06-2019 a las 18:54:22
-- Versión del servidor: 10.1.36-MariaDB
-- Versión de PHP: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `afinal`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `anime`
--

CREATE TABLE `anime` (
  `idAni` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `episode` int(11) NOT NULL,
  `category` varchar(20) NOT NULL,
  `description` text NOT NULL,
  `cover` varchar(255) NOT NULL,
  `start_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `anime`
--

INSERT INTO `anime` (`idAni`, `name`, `episode`, `category`, `description`, `cover`, `start_date`) VALUES
(1, 'Nanatsu No Taizai', 26, 'Serie', 'Los “Siete Pecados Capitales”, un grupo de caballeros malignos que conspiraron para derrocar al Reino de Britania, se dice que fueron erradicados por los Caballeros Sagrados, aunque algunos dicen que aún viven. Diez años después, los Caballeros Sagrados dieron un golpe de estado y asesinaron al rey, convirtiéndose en los nuevos y tiránicos regidores del reino. Elizabeth, la única hija del rey, emprende un viaje para encontrar a los “Siete Pecados Capitales” y conseguir su ayuda para recuperar el reino.', 'https://animeflv.net/uploads/animes/covers/1620.jpg', '2014-10-05'),
(2, 'Boku No Hero Academy', 13, 'Serie', 'Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?\r\n\r\n', 'https://animeflv.net/uploads/animes/covers/2430.jpg\r\n', '2016-04-03'),
(3, 'Bleach', 366, 'Serie', 'Kurosaki Ichigo es un estudiante de instituto de 15 años, que tiene una peculiaridad: es capaz de ver, oír y hablar con fantasmas. Pero no sabe hasta dónde puede abarcar la clasificación de espíritus, ni lo que conlleva el saberlo. Un buen día, una extraña chica de pequeña estatura que viste ropas negras de samurai entra en su cuarto. Se llama Rukia Kuchiki, y es una Shinigami (Dios de la Muerte). Ante la incredulidad de Ichigo, le explica que su trabajo es mandar a las almas buenas o plus a un lugar llamado la Sociedad de Almas, y eliminar a las almas malignas o hollows. Luego junto a Inoue Orihime, Ishida Ury y Sado Yasutora se veran envueltos en diferentes batallas, las cuales iran desarrollando sus diferentes habilidades que le otorgaran a cada uno su importancia en la serie.', 'https://animeflv.net/uploads/animes/covers/1.jpg', '2004-10-05'),
(4, 'Kimi no Na wa', 1, 'Película', 'La “historia de milagros y amor” gira en torno a Mitsuha y Taki. Mitsuha es una estudiante de secundaria que vive en un pueblo rural situado en las montañas. Su padre es el alcalde y no pasa mucho por casa, ella vive con su hermana pequeña estudiante de primaria y su abuela. Mitsuha tiene una personalidad honesta, pero a ella no le gustan las costumbres del santuario sintoísta de su familia, ni ella ni su padre participan en una campaña electoral. Ella se lamenta de que vive confinada en un pueblo rural y anhela el maravilloso estilo de vida de Tokio. Taki es un estudiante de secundaria que vive en el centro de Tokio. Él pasa su tiempo junto a sus amigos, trabajando a tiempo parcial en un restaurante italiano y está interesado en la arquitectura y las bellas artes. Un día, Mitsuha tiene un sueño en el que ella tiene el cuerpo de un hombre joven. Taki también tiene un sueño parecido y en el que él es una estudiante de secundaria en un pueblo en las montañas en él que nunca ha estado. ¿Cuál es el secreto de sus sueños?', 'https://animeflv.net/uploads/animes/covers/2543.jpg', '2016-08-26'),
(5, 'Naruto Shippuden', 500, 'Serie', 'Pasados dos años y medio de entrenamiento con Jiraiya, Naruto Uzumaki regresa a la aldea oculta de la hoja, donde se reúne con sus viejos amigos y conforma de nuevo el Equipo 7. Debido a la ausencia de Sasuke, aparece un nuevo personaje llamado Sai el cual retoma su lugar. En esta secuela podremos notar como los compañeros de Naruto han madurado con respecto a su desempeño previo, mejorando la mayoría de estos en su nivel. Durante su entrenamiento con Jiraiya, Naruto aprendió a controlar un poco de la chacra del Kyubi. Lo contrario a la serie original, dónde sólo desempeñó un papel secundario, la organización Akatsuki asume el papel antagónico principal en Naruto Shippuden, buscando como objetivo principal el capturar a todos los poderosos monstruos Biju.', 'https://animeflv.net/uploads/animes/covers/3.jpg', '2007-02-15'),
(6, 'Naruto', 220, 'Serie', 'Naruto, un aprendiz de ninja de la Aldea Oculta de Konoha es un chico travieso que desea llegar a ser el Hokage de la aldea para demostrar a todos lo que vale. Lo que descubre al inicio de la historia es que la gente le mira con desconfianza porque en su interior está encerrado el demonio Kyubi que una vez destruyó la aldea, y que el anterior líder de la misma tuvo que encerrar en su cuerpo siendo aún muy pequeño, a coste de su vida. Aunque sus compañeros no saben esto, tampoco le aprecian porque es mal estudiante y siempre está haciendo bromas. Sin embargo, la forma de actuar y la determinación de Naruto demuestran a los demás que puede llegar muy lejos, y el recelo de los otros chicos se va disipando. Naruto y sus compañeros Sakura y Sasuke, junto a su maestro Kakashi tendrán que enfrentarse a una serie de combates y misiones a lo largo de la historia que les permitirán mejorar y crecer. Naruto se vera enfrentado a sus principales enemigos Akatsuki, Itachi y Kisame.', 'https://animeflv.net/uploads/animes/covers/2.jpg', '2002-10-03'),
(7, 'Dragon Ball Z', 291, 'Serie', 'En Dragon ball Z Goku se ha convertido en un adulto y está casado con Milk, con la que tiene un hijo llamado Gohan. En esta segunda saga de Dragon ball Goku descubrirá que no es un terricola, sino que pertenece a una raza de guerreros conocida por ser una de las más poderosas de la galaxia, para posteriormente dar paso a los verdaderos enemigos de la serie. Para poder vencer a los nuevos enemigos que irán surgiendo, Goku y sus amigos tendrán que viajar por otros planetas e incluso al cielo y al infierno. Cada enemigo será más fuerte que el anterior, por lo que tendrán que entrenar muy duro para poder derrotarlos además de que se les irán uniendo nuevos personajes que les ayudarán a vencerlos.', 'https://animeflv.net/uploads/animes/covers/37.jpg', '1989-04-26'),
(8, 'Dragon Ball', 153, 'Serie', 'Con Goku como protagonista principal de la historia, el argumento se centra en la búsqueda de las legendarias esferas del dragon, un total de siete que al ser reunidas daban lugar a la aparición del dragón sagrado que puede conceder cualquier deseo. Goku, con la ayuda de su compañera Bulma además de otros personajes que se irán uniendo con el paso de la historia, se adentrará en la búsqueda de las esferas del dragon y desafiará a todo tipo de villanos para convertirse en el hombre más fuerte del mundo. También se hará especial incapié al Budokai Tenkaichi, un gran Torneo Mundial de Artes Marciales en el que los mejores luchadores de todo el Mundo se darán cita, batiéndose en Duelo a fin de demostrar quien es el mas fuerte luchador sobre la Tierra.', 'https://animeflv.net/uploads/animes/covers/509.jpg', '1986-02-26'),
(9, 'Dragon Ball GT', 64, 'Serie', 'Ésta es la etapa final de Dragon Ball, aquí veremos a un Goku un poco más viejo acompañado de Oob, la reencarnación de Boo. Ahora Oob, después de un largo entrenamiento, se ha vuelto muy fuerte junto a Goku. Ahora un nuevo problema se le presenta a Goku, él ha sido convertido en niño por un viejo enemigo, con unas esferas de dragón nunca antes vistas, pero éstas no se esparcen por La Tierra, si no por la galaxia, además, si no encuentran las esferas en un determinado tiempo, La Tierra explotará. Esto llevará a Goku, Trunks y su nieta Pan, a una aventura por toda la galaxia.', 'https://animeflv.net/uploads/animes/covers/451.jpg', '1996-02-07'),
(10, 'Boku no Hero Academia the Movie: Futari no Hero', 1, 'Película', 'En el extranjero existe una ciudad gigante, flotante, creada por el hombre: I Island. La película tendrá lugar tras el arco del examen final, en verano, pero antes del arco de entrenamiento del bosque. Asimismo, se revelará más información del pasado de All Might.', 'https://animeflv.net/uploads/animes/covers/3103.jpg', '2018-08-03'),
(11, 'Nanatsu no Taizai: Imashime no Fukkatsu', 24, 'Serie', 'Los Sietes Pecados Capitales son un grupo de caballeros considerados los más fuertes de Britannia. Este grupo fue formado por Meliodas y Merlín. Al cabo de un tiempo, y tras servir al reino anteriormente nombrado, se les acusó de cometer cierto crimen y tuvieron que huir por ser acusados de traidores. Melodias le pidió a cada uno que se marchara individualmente para que no los atraparan.\r\n\r\nAl cabo de un tiempo, Elizabeth, una de las princesas del reino de Liones, conoce a Meliodas de una manera curiosa. El capitán de los Pecados le confiesa quien es y ella le cuenta que quiere reunirlos porque son el escuadrón más fuerte conocido del reino. Tras reunirlos a todos y descubrir quién estaba detrás de los planes malvados que acechaban al reino, pelean contra los Caballeros Sagrados demoniacos. Finalmente, se alzan con la victoria o eso creen.', 'https://animeflv.net/uploads/animes/covers/2895.jpg', '2018-01-13'),
(12, 'Tokyo Ghoul', 12, 'Serie', 'Extraños asesinatos se están sucediendo uno tras otro en Tokyo. Debido a las pruebas encontradas en las escenas, la policía concluye que los ataques son obra de ghouls que se comen a las personas. Kaneki y Hide, dos compañeros de clase, llegan a la conclusión de que si nadie ha visto nunca a esos necrófagos es porque toman la apariencia de seres humanos para ocultarse. Poco sabían entonces de que su teoría sería más cierta de lo que pensaban cuando Kaneki es herido de gravedad por un monstruo y comienza a atraerle cada vez más la carne humana…', 'https://animeflv.net/uploads/animes/covers/1415.jpg', '2014-07-04'),
(13, 'Katekyo Hitman Reborn', 203, 'Serie', 'Tsunayoshi Sawada (Tsuna) era un chico normal hasta que su pariente Timoteo (el 9º capo de la familia Vongola) le comunica que él va a ser su sucesor. Para que Tsuna este preparado para el momento en el que el sea el 10º capo, manda a su casa a un tutor personal llamado Reborn que le ayudara a ser un buen capo gracias a un arma especial de la familia Vongola, y que en ciertas ocasiones le ayudara a continuar su vida normal de una sola pieza. Luego aparecieran mas personajes que le harán la vida mas difícil y a la vez mas divertida a Tsuna.', 'https://animeflv.net/uploads/animes/covers/301.jpg', '2006-10-07'),
(14, 'Pokemon', 276, 'Serie', 'El anime de Pokémon es uno de los pocos que es basado en un videojuego debido a la popularidad de este. La historia del anime esta centrada en un chico de 10 años llamado Ash Ketchum. Este muchacho tiene el sueño de llegar a ser el mejor entrenador Pokémon del mundo. La historia empieza exactamente la noche anterior a que este muchacho empezara su viaje. Este chico vive en Pueblo Paleta con su madre (del padre no se sabe nada). En este pueblo también vive una autoridad del mundo Pokémon, el Profesor Oak, quien le entrega a todos los nuevos entrenadores su primer Pokémon y una herramienta llamada Pokedex (una enciclopedia de alta tecnología con información sobre todos los Pokémon), es esta persona quien le da su primer Pokémon a Ash, como ustedes bien sabrán, un Pikachu.', 'https://animeflv.net/uploads/animes/covers/944.jpg', '1997-04-01'),
(15, 'Boku No Hero Academy 2nd', 25, 'Serie', 'Segunda temporada de Boku no Hero Academy.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21856-I9rVZElYPVUE.png', '2017-04-01'),
(16, 'Boku No Hero Academy 3rd', 25, 'Serie', 'Tercera temporada de Boku no Hero Academy.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx100166-TxwbUGculKAX.jpg', '2018-04-07'),
(17, 'Inuyasha', 167, 'Serie', 'Se basa en la historia de una joven llamada Kagome (Aome en latino) que al cumplir 15 años viaja atraves del tiempo por medio de un pozo mágico (que se encuentra en un templo que esta en su casa) hasta regresar a la época de las guerras civiles es allí donde encuentra al personaje principal (Inuyasha). Kagome es la reencarnación de la sacerdotisa Kikyo quien era la poseedora de una perla muy poderosa que villanos y demonios quieren para hacerse mas poderosos llamada la perla de Shikon: Kagome tenia esta perla en sus interior y sale al ambiente debido a que un demonio se la quita depues la perla es cortada en miles de pedazos que se dispersan con la tierra y ahora Inuyasha y Kagome tiene que recolectar estos fragmentos para evitar que caigan en manos equivocadas en esto pasaran por muchas aventuras conocerán amigos y enemigos tendran batallas algunas veces estarán en peligro de morir. Alo largo de la historia se hacen notar historias antiguas que tiene que ver con la perla.\r\n', 'https://animeflv.net/uploads/animes/covers/53.jpg', '2000-11-16'),
(18, 'Inuyasha: Kanketsu-hen', 26, 'Serie', 'Los esbirros de Naraku trataran de rebelarse en contra de el ahora que ha perdido su corazón, pero Naraku tiene todo bajo control y no caerá tan fácilmente. Seshomaru busca dejar su ambición por las espadas de su padre en busca de su propia arma, al mismo tiempo el corazón de Inuyasha sigue en la cuerda floja entre Kagome y Kikyo, al mismo tiempo que intenta protegerlas a las dos, por su parte Kikyo intenta completar la perla para purificarla junto con Naraku, Miroku y Sango tomarán difíciles decisiones impulsadas por su amor.\r\n', 'https://animeflv.net/uploads/animes/covers/942.jpg', '2009-10-04'),
(19, 'Inuyasha: Guren no Houraijima', 1, 'Película', 'La isla misteriosa de Hourijima ha reaparecido después de 50 años, y esta reaparición ha traído el ataque de cuatro dioses,hermanos entre sí, uno de ellos llamado Shitoushin, cuyo poder es indescriptible. Ahora todo depende de Inuyasha y sus amigos, junto con Sesshomaru, de encontrar una manera de derrotar al poderoso Shitoushin y así salvar la vida de los habitantes de la isla.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/449.jpg', '2004-12-23'),
(20, 'Fairy Tail', 175, 'Serie', 'Fairy Tail cuenta la historia de un joven mago llamado Natsu en la búsqueda de su maestro y padre adoptivo Igneel que resulta ser un dragón. Por ello se unió a Fairy Tail, un gremio de magos que es famoso por los destrozos y daños que provocan en diversas ciudades (lo cual no debería ser así). El mundo de Fairy Tail gira alrededor de los magos (los cuales poco tienen que ver con la idea general del mago común) que realizan encargos a cambio de dinero, similar a un cazarecompensas. Natsu conoce a Lucy, una guapa muchacha cuyo sueño era ingresar a un gremio de magos, específicamente, a Fairy Tail, lo cual consigue gracias a la ayuda de Natsu. De ahí en adelante, la historia sigue los movimientos de esta pareja de magos los cuales se ven envueltos en un sin número de aventuras antes de conseguir la meta final de encontrar a Igneel.\r\n', 'https://animeflv.net/uploads/animes/covers/5.jpg', '2009-10-12'),
(21, 'Fairy Tail 2nd', 102, 'Serie', 'Los Grandes juegos mágicos alcanzan su culmen, después de la impresionante victoria de Natsu Dragneel y Gajeel Redfox sobre Sting Eucliffe y Rogue Cheney, del gremio de Sabertooth. Este éxito empuja al gremio de Fairy Tail más cerca de ser coronado como campeón, pero obtener la victoria no es el único desafío que enfrentan. Un misterio rodea a un desconocido encapuchado y la amenazante Puerta de Eclipse, dejando más preguntas que respuestas.\r\n\r\nLas aventuras más locas están en el horizonte para Fairy Tail, ya que sus travesuras destructivas y su alegre amistad continúan sin cesar. Su mayor prueba aparece más pronto que nunca, pero unidos como una familia, el gremio siempre estará listo para enfrentar cualquier amenaza que se les presente.', 'https://animeflv.net/uploads/animes/covers/1290.jpg', '2014-04-05'),
(23, 'Fairy Tail: Houou no Miko ', 1, 'Película', 'Una misteriosa chica llamada Éclair aparece ante Fairy Tail. Ella ha perdido todos sus recuerdos, excepto la orden de enviar dos Hōōseki (Rocas Fénix) a algún lugar. Sin embargo, las rocas podrían causar el colapso del mundo mágico.\r\n', 'https://animeflv.net/uploads/animes/covers/937.jpg', '2012-08-18'),
(24, 'Faity Tail: Dragon Cry.', 1, 'Película', 'Dragon Cry, un poderoso artefacto mágico capaz de destruir al mundo ha sido robado. Zash traidor al Reino de Fiore lo ha entregado al Reino de Stella. Natsu y los Magos del Gemio de Fairy Tail tendrán que recuperar este místico objeto antes de que sea demasiado tarde ¿Qué peligros los esperan?\r\n', 'https://animeflv.net/uploads/animes/covers/2852.jpg', '2017-05-06'),
(25, 'Cardcaptor Sakura', 70, 'Serie', 'Sakura Kinomoto es una niña de 10 años que vive con su padre Fujitaka y su hermano Touya. La historia comienza cuando Sakura abre un extraño libro llamado The Clow y libera accidentalmente las cartas que este contenía, Sakura deberá pasar grandes apuros para sellar las cartas pero con ayuda de sus amigos Tomoyo, Shaoran y Kerberos vivirían grandes aventuras para lograr su objetivo, atrapar todas las cartas Clow.\r\n', 'https://animeflv.net/uploads/animes/covers/447.jpg', '1998-04-07'),
(26, 'Cardcaptor Sakura: Clear Card-hen', 22, 'Serie', 'Guiada por la Llave de los Sueños, Sakura se embarca en una nueva aventura. Sakura logró capturar todas las Cartas de Clow que podrían haber provocado un cataclismo en el mundo y las convirtió en sus Cartas de Sakura. Ahora ha llegado la primavera, los cerezos están en flor y Sakura está por comenzar una nueva etapa en la secundaria. Su querido Syaoran ha regresado de Hong Kong y Sakura está muy ilusionada por poder ir a clase de nuevo con él. Es entonces cuando una noche ocurre algo extraño a sus cartas...\r\n', 'https://animeflv.net/uploads/animes/covers/2870.jpg', '2018-01-07'),
(27, 'Shaman King', 64, 'Serie', 'La historia empieza cuando Manta Oyamada, un estudiante de secundaria, que pasa por el cementerio local porque se le hace tarde, y divisa a un joven misterioso que simplemente observa las estrellas. Yoh Asakura le invita a quedarse con él y sus amigos a verlos, Manta huye asustado a ver que los amigos eran fantasmas. Manta le cuenta a sus \"amigos\" lo ocurrido y ellos no le creen. Después, Yoh decidió ser amigo de Manta, a pesar de que al principio Manta le tenia miedo a Yoh.\r\n', 'https://animeflv.net/uploads/animes/covers/84.jpg', '2001-07-04'),
(28, 'Fruits Basket', 26, 'Serie', 'Honda Toru es una estudiante que después de la muerte de su madre decide vivir sola en una tienda de campaña en el bosque, propiedad de la familia Soma. Una noche es encontrada por Yuki Soma, el \"príncipe\" de su escuela, este y su primo Shigure le piden que viva con ellos. Dentro de la casa conoce a Kyo, otro integrante de la familia Soma y la terrible maldición que pesa sobre ellos que consiste que al ser abrazados por el sexo opuesto se transforman en animales del zodiaco chino (a excepción de Kyo que es el gato).\r\n', 'https://animeflv.net/uploads/animes/covers/1392.jpg', '2001-07-05'),
(29, 'Fullmetal Alchemist', 51, 'Serie', 'Tras perder a su madre, Alphonse y Edward Elric tratan de revivirla usando la ciencia prohibida de la alquimia humana. Sin embargo, la alquimia opera bajo la teoría del cambio equivalente y romper el tabú de la alquimia humana acarrea un alto precio. Ed pierde una de sus piernas y Al su cuerpo. Ed logra sellar el alma de Al dentro de una gran armadura, a costa de su brazo. Años después, Ed (ahora con dos extremidades mecánicas) y Al (aún atrapado en la armadura) dejan su casa de la niñez, cada uno preocupado por la felicidad del otro. Ed, quien tuvo un talento y habilidad natural para la alquimia, se convierte en un alquimista con certificado nacional y pronto es conocido en todas partes como el ?Alquimista Fullmetal?. El verdadero objetivo de ambos hermanos es buscar cualquier información sobre la legendaria Piedra Filosofal, con la esperanza de que ésta les permita recobrar sus cuerpos. Todas sus esperanzas descansan en la mítica piedra, que incluso puede no existir.\r\n', 'https://animeflv.net/uploads/animes/covers/40.jpg', '2003-10-04'),
(30, 'Fullmetal Alchemist: Brotherhood', 64, 'Serie', 'La historia se centra en dos hermanos, Edward Elric y Alphonse Elric que rompieron el mayor tabú de la alquimia, la trasmutación humana al tratar de revivir a su fallecida madre; en consecuencia Edward pierde su pierna izquierda y Alphonse pierde todo su cuerpo, Edward para salvar a su hermano sella su alma en una gran armadura de hierro a cambio de su brazo derecho; ahora los dos con un nuevo objetivo buscan desesperadamente la piedra filosofal para poder regresar sus cuerpos a la normalidad...\r\n', 'https://animeflv.net/uploads/animes/covers/39.jpg', '2009-04-05'),
(31, 'Magi: The Labyrinth of Magic', 25, 'Serie', 'Esta historia es sobre la corriente del destino y la lucha para mantener el mundo en el camino correcto. Aladin es un chico que ha estado explorando el mundo luego de haber estado encerrado en una habitación la mayor parte de su vida. Su mejor amigo es una flauta con un Djinn (Genio) llamado Ugo dentro de ella. En poco tiempo Aladin descubre que es un Magi (mago), y que ha nacido para escoger reyes que sigan un camino justo, y que luchen contra aquellos que quieren destruir el destino. Sigue sus aventuras y conoce a otros personajes de ?Las Mil y Una Noches?, como Alibaba, Sinbad y sus luchas para mantener el equilibrio del mundo.\r\n', 'https://animeflv.net/uploads/animes/covers/876.jpg', '2012-10-07'),
(32, 'Magi: The Kingdom of Magic', 25, 'Serie', 'Después de celebrar su victoria contra Al-Thamen, Aladdin y sus amigos salen de la tierra de Sindria. Con el fin de la batalla, sin embargo, llega el momento de que cada uno de ellos coja su camino por separado. A Hakuryuu y Kougyoku se les ordena regresar a su país de origen, el Imperio Kou. Mientras tanto, Aladdin anuncia que necesita dirigirse a Magnostadt, un país misterioso gobernado por magos, para investigar los eventos misteriosos que ocurren en este nuevo reino y adquirir más habilidad en la magia. Por su parte, alentados por las palabras de Aladdin, Alibaba y Morgiana también emprendieron la búsqueda de sus propios objetivos: entrenar e ir a su tierra natal, respectivamente.', 'https://animeflv.net/uploads/animes/covers/1154.jpg', '2013-10-07'),
(33, 'ReLife', 13, 'Serie', 'La historia está protagonizada por Arata Kaizaki, un hombre de 27 años, soltero y desempleado al que sus padres le dejan sin apoyo financiero. Incapaz de encontrar trabajo debido a que siempre abandonó sus empleos anteriores en menos de tres meses, no sabe qué hacer. Una noche, tras estar bebiendo con un viejo amigo del instituto, Arata conoce a Ryo Yoake, un hombre que le ofrece a Arata una pastilla que lo convertirá nuevamente en un adolescente de 17 años y así poder rehacer su vida. Tras acceder a hacer la prueba, Arata se une a una nueva clase en el instituto y conoce a Chizuru Hishiro, una preciosa chica pero muy silenciosa que anhela tener amigos. Arata tendrá que interactuar con la chica y el resto de sus nuevos compañeros de clase para descubrir qué le falta en su vida para ser feliz en el año que durará el efecto de la pastilla.\r\n', 'https://animeflv.net/uploads/animes/covers/2483.jpg', '2016-07-02'),
(34, 'ReLIFE: Kanketsu-hen', 4, 'OVA', 'Arco Argumental en los que se adapta el final de la serie(Manga).', 'https://animeflv.net/uploads/animes/covers/2907.jpg', '2018-03-21'),
(35, 'Tokyo Ghoul Re', 12, 'Serie', 'Dos años después del ataque del CCG al Anteiku, la ciudad de Tokio cambia drásticamente debido a la influencia del CCG. Además, los ghouls siguen siendo un problema, pues ahora se han vuelto más cautos. Sin embargo, se creará la nueva escuadra experimental Quinx para mantenerlos a raya, un grupo liderado por un mitad ghoul, mitad humano.\r\n', 'https://animeflv.net/uploads/animes/covers/2917.jpg', '2018-04-03'),
(36, 'Tokyo Ghoul √A', 12, 'Serie', 'Segunda temporada de Tokyo Ghoul.', 'https://animeflv.net/uploads/animes/covers/1785.jpg', '2015-01-09'),
(37, 'Tokyo Ghoul: Re 2nd ', 12, 'Serie', 'Segunda temporada de Tokyo Ghoul: Re', 'https://animeflv.net/uploads/animes/covers/3014.jpg', '2018-10-12'),
(39, 'Sword Art Online', 25, 'Serie', 'Escapar es imposible hasta terminar el juego; un game over significaría una verdadera \"muerte\". Sin saber la \"verdad\" de la siguiente generación del Multijugador Masivo Online, \'Sword Art Online(SAO)\', con 10 mil usuarios unidos juntos abriendo las cortinas para esta cruel batalla a muerte. Participando solo en SAO, el protagonista Kirito ha aceptado inmediatamente la \"verdad\" de este MMO. Y, en el mundo del juego, un gigante castillo flotante llamado \'Aincrad\', Kirito se distinguió a si mismo como un jugador solitario. Apuntando a terminar el juego al alcanzar la planta mas alta el solo continua avanzando arriesgadamente hasta que recibe una invitación a la fuerza de una guerrera y esgrimista experta, Asuna, con la cual tendra que hacer equipo.\r\n', 'https://animeflv.net/uploads/animes/covers/825.jpg', '2012-07-08'),
(41, 'Sword Art Online II', 24, 'Serie', 'Phantom Bullet transcurre un año después de completarse SAO, cuando Kirito recibe una llamada del investigador Seijirou Kikuoka para hablar de un extraño caso relacionado con el juego Gun Gale Online. Un misterioso jugador llamado Death Gun es capaz de matar a personajes en el juego y, a su vez, matar a quienes los controlan en el mundo real. Kirito entrará en el juego para investigar cómo es eso posible y allí conocerá a Sinon, que será su guía en este nuevo mundo.\r\n', 'https://animeflv.net/uploads/animes/covers/1421.jpg', '2014-07-05'),
(42, 'Sword Art Online Movie: Ordinal Scale', 1, 'Película', 'La película tiene lugar tras los hechos acontecidos en la segunda temporada animada. Kirito, Asuna y sus amigos empiezan a jugar a un nuevo juego conocido como OS (Ordinal Scale) que, a diferencia de los juegos anteriores, utiliza un sistema de realidad aumentada llamado Augma. En este juego, los jugadores se clasifican de acuerdo a sus rangos por lo que los jugadores con rangos inferiores tienen grandes desventajas. Sin embargo, Kirito y sus amigos descubren que algo va mal cuando se encuentran con monstruos de Aincrad.\r\n', 'https://animeflv.net/uploads/animes/covers/2734.jpg', '2017-02-18'),
(43, 'Sword Art Online: Alicization', 24, 'Serie', '\"¿Dónde estoy...?\". Sin recordar cómo, Kirito se ha sumergido en un nuevo mundo virtual de fantasía. Con apenas unos pequeños retazos de recuerdos sobre lo que ocurrió antes de entrar al juego, comienza a vagar por él buscando alguna pista. Finalmente llega a un enorme y oscuro árbol, el Cedro Gigas, donde conoce a un joven. \"Me llamo Eugeo. Es un placer conocerte, Kirito\". Aunque es supuestamente un habitante de ese mundo virtual, un mero NPC, el joven parece mostrar el mismo abanico de emociones que cualquier ser humano. Kirito forja amistad con Eugeo y continúa buscando la forma de salir de este mundo virtual. Es entonces cuando recuerda algo que ocultaba en su interior. Recuerda haber corrido por las montañas con Eugeo cuando solo era un niño... Un recuerdo imposible que no debería tener, y en ese recuerdo ve también a una niña de cabellos rubios: Alice. Ese es un nombre que nunca deberá olvidar...\r\n', 'https://animeflv.net/uploads/animes/covers/3040.jpg', '2018-10-07'),
(44, 'Sword Art Online: Extra Edition', 1, 'OVA', 'Kirito y el resto decide lanzarse a una misión acuática dentro del mundo de ALO para que Yui pueda cumplir su deseo de ver una ballena. Mientras se preparan para partir, descubren algo que les deja impactados... a Leafa, o Suguha, le da miedo el agua. Con ello, Asuna y el resto de chicas del grupo deciden enseñar a Suguha a nadar en una piscina en el mundo real. Mientras tanto, Kirito se encuentra con alguien...\r\n', 'https://animeflv.net/uploads/animes/covers/1199.jpg', '2013-12-31'),
(45, 'Digimon 01 Adventure', 54, 'Serie', 'Siete niños disfrutan de sus vacaciones de verano en un campamento, cuando de repente, se ven envueltos en un misterios mundo: El Mundo Digital. Un mundo paralelo al suyo formado a partir de datos digitales. Allí conocen a sus compañeros los digimon, y juntos tendrán que solucionar los extraños sucesos que aterran la Isla File, provocados por Devimon. Pero tal vez no sea esa el único motivo por el que aparecieron en aquél misterioso mundo, tendrán que afrontarse a más de una aventura para descubrirlo y volver a su mundo original.\r\n', 'https://animeflv.net/uploads/animes/covers/33.jpg', '1999-03-07'),
(46, 'Digimon 02 Zero Two', 50, 'Serie', 'Es la secuela de Digimon Adventure, han pasado tres años desde que volvieron desde el digiworld cuando T.K. y Kari son llevados de vuelta junto a otros tres nuevos niños elegidos, que consiguen sus digimon cada uno. Despues, consiguen los llamados digieggs que les permite digievoluciones especiales y se enfrentan al emperador un niño elegido que intenta apoderarse de todo el digimundo.\r\n', 'https://animeflv.net/uploads/animes/covers/130.jpg', '2000-04-02'),
(47, 'Digimon Adventure Tri 1: Saikai', 4, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx20802-nS7xOnP7XzJV.jpg', '2015-11-21'),
(48, 'Digimon Adventure Tri 2: Ketsui', 4, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21500-xWyYJaRmUmR1.jpg', '2016-03-12'),
(49, 'Digimon Adventure Tri 3: Kokuhaku', 6, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21596-r1NLhNiSD2Ki.jpg', '2016-09-24'),
(50, 'Digimon Adventure Tri 4: Soushitsu', 4, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/97734-5CBTXhocIxpw.jpg', '2017-02-25'),
(51, 'Digimon Adventure tri. 5: Kyousei', 4, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx98402-T6S8TnRJhAwC.jpg', '2017-09-30'),
(52, 'Digimon Adventure tri. 6: Bokura no Mirai', 4, 'Película', 'Quince años después de las vacaciones de verano. Si no hubiéramos ido al Mundo Digital. Si no hubiéramos hecho este viaje con los otros. Si no hubiéramos cambiado de esta manera. Estos Digimon siempre estuvieron con nosotros. Fuimos amigos todo el tiempo. Aprendimos la importancia de ayudarnos mutuamente. ¡Todas esas cosas nos hicieron como somos! Nuevas aventuras para todos los “Niños Elegidos” en el mundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx100181-oTwznKIAT1vb.jpg', '2018-05-05'),
(53, 'Digimon 03 Tamers', 51, 'Serie', 'Digimon Adventure y Adventure 02 han sido para muchos niños una gran serie de anime, incluso se ha sacado un juego muy popular de cartas en Japón, uno de esos niños es Takato Matsuda, el cual sueña con tener su propio Digimon. Un día, mientras Takato juega con cartas, se encuentra con una carta azul muy extraña que jamas había visto antes, carta que luego transforma su digi-device y le permite crear su propio Digimon, junto con amigos comenzaran increíbles aventuras tanto en el mundo real como en el Digimundo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/874-wJAeOR3nlQM7.jpg', '2001-04-01'),
(54, 'Digimon 04 Frontier', 50, 'Serie', 'Después de recibir un mensaje en sus celular Takuya es llevado por un tren al Digiworld junto con otros 4 niños, Koji, Zoe, J.P. y Tommy, allí son guiados por Bokomon y Naemon para encontrar los digispirits que les permitirán a Takuya y sus amigos digievolucionar en los guerreros legendarios y asi enfrentar a Cherubimon\r\n', 'https://animeflv.net/uploads/animes/covers/948.jpg', '2002-04-07'),
(55, 'Digimon 05 Savers', 48, 'Serie', 'Masaru Daimon, un chico de 17 años con bastante temperamento, se encuentra inesperadamente con Agumon, un digimon que había escapado de la organización gubernamental secreta DATS. Estos se retan a una pelea, llegando a un empate, por lo que terminan aceptándose el uno al otro, haciéndose amigos. Es cuando comienzan a aparecer digimons en la ciudad, causando estragos. Tras vencer Masaru a Kokatorimon, él y su reciente amigo Agumon, son detenidos y llevados al cuartel de DATS. Esta organización tiene como misión principal la de bloquear la acción de cualquier digimon que aparezca en el mundo real de la manera más silenciosa, llevándolos de vuelta al mundo digital de donde provienen y borrando las memorias de los ciudadanos que han llegado a ver a uno de estos seres. Por tanto, la existencia de los digimon sólo es conocida por los miembros de DATS, de la que Masaru termina formando parte.\r\n', 'https://animeflv.net/uploads/animes/covers/1575.jpg', '2006-04-02'),
(56, 'Digimon Xros Wars', 54, 'Serie', 'Taiki Kudou es un estudiante de septimo grado prodigio, q siempre lo gana todo. Un dia el escucha una voz misteriosa que le pide ayuda y empiezan a ocurrir sucesos extraños en ese momento, al encontrar al que le pide ayuda, Shoutmon un Digimon Melodia, se le aparece en frente de el \"LoaderXross\" (digivice de esta temporada) y lo elige para poder salvar el digimundo. Fue así que Taiki junto a sus amigos Akari Hinomoto y su rival Zenjirou Tsurugi se lanzan a un universo paralelo, el mundo digital (Digimundo) para asi poder ayudar a Shoutmon y a sus amigos Digimon para poder formar un ejercito para la guerra \"Xross Wars\" y asi salvar al digimundo de las nuevas fuerzas del mal que lo amenazan...\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/8624.jpg', '2010-07-06'),
(57, 'Another: The Other - Inga', 1, 'OVA', 'Episodio 0 incluido en el volumen número 0 de edición limitada de la adaptación de manga de Kiyohara Hiro de la novela de terror Ayatsuji Yukito Otra.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/n11701-38Cagq35wkpY.jpg', '2012-05-26'),
(58, 'Final Fantasy', 1, 'OVA', 'Una continuación de los eventos de Final Fantasy V. 200 años después de que Bartz y sus amigos salvaran dos mundos de la amenaza de ExDeath, surge una amenaza y busca tomar los Cristales por sí mismo. Linaly, descendiente de Bartz, y su amigo / protector Prettz viajan al Templo del Viento para buscar la fuente de este nuevo peligro.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/426.jpg', '1994-03-21'),
(59, 'Brotherhood Final Fantasy XV ', 5, 'OVA', 'BROTHERHOOD FINAL FANTASY XV se adentra en las extraordinarias amistades entre el Príncipe Noctis y sus tres compañeros, preparando el escenario para la aventura que los jugadores emprenderán en este juego de rol lleno de acción.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21728-NrURLwZVRaNf.jpg', '2016-03-31'),
(60, 'Final Fantasy: Advent Children', 1, 'Película', 'Dos años después del final de Final Fantasy VII, el mundo está comenzando a recuperarse y está trabajando hacia un nuevo futuro. Sin embargo, hay una nueva amenaza de una nueva enfermedad llamada Geo-estigma, y ​​tres hombres que parecen estar buscando a Jenova. Cloud y sus amigos del juego original deben reunirse una vez más para combatir la nueva amenaza.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b317-ay0Rw7kxgLVD.jpg', '2005-09-14'),
(61, 'Final Fantasy VII: Last Order', 1, 'Película', 'Después de la destrucción de Nibelheim a manos de Sephiroth, Zack y Cloud huyen de Shinra Inc. Mientras regresan a Midgar, recuerdan los horribles eventos que ocurrieron en Nibelheim y luchan por sobrevivir contra Shinra.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/408.jpg', '2015-09-14'),
(62, 'Hunter x Hunter: Greed Island Final ', 14, 'OVA', 'Continuando con su aventura en Greed Island, Gon y Killua se entrenan furiosamente bajo la guía de Biscuit para prepararse mejor para intentar el juego. Con sus habilidades enormemente mejorando y la amenaza de asesinos de jugadores que amenazan a Greed Island, Gon y compañía continúan el juego a pesar de los peligros que enfrentarán con las actividades del juego y los encuentros con otros jugadores. Basado en el manga de Togashi Yoshihiro.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/139-nfieU7SpC6XG.jpg', '2004-03-03'),
(63, 'Final Fantasy VII: On the Way to a Smile - Episode: Denzel ', 1, 'OVA', 'Novela final de Final Fantasy VII On the Way to a smile Episodio: Denzel se adaptará a un anime para el lanzamiento de Final Fantasy VII: Advent Children Complete el 16 de abril. El anime se enviará como un suplemento adicional en los lanzamientos de discos de Blu-ray de Advent Children\'s . La parte de Denzel de En el camino a una historia de sonrisas comienza cuando el personaje que Denzel pretende enlistarse en la Organización Mundial de la Regénesis (WRO) y \"salta\" de vuelta al pasado de Denzel.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/6151.jpg', '2009-04-16'),
(64, 'Fushigi Yuugi', 3, 'OVA', 'Un año después de los eventos de Fushigi Yuugi, Tamahome regresa al libro y se la envía en un viaje complicado a través de la ilusión, la confusión y la traición. Mientras tanto, Yui está actuando de manera extraña y Miaka está desconsolada por la pérdida de Tamahome, mientras que Keisuke y Tetsuya intentan descubrir qué está pasando con el libro.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/380.jpg', '1996-06-25'),
(65, 'Fushigi Yuugi: Eikoden ', 4, 'OVA', 'Taka (técnicamente Tamahome) y Miaka ahora están felizmente casados ​​y solo seis meses antes de que naciera su nueva familia, pero una niña obesa llamada Mayo haría cualquier cosa por hacer de Taka suya. Ella entra en el mundo de los Cuatro Dioses, decidida a ganarse el corazón de Taka y ser la nueva sacerdotisa.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/124.jpg', '2001-12-21'),
(66, 'Little Busters! EX ', 8, 'OVA', 'Las adiciones principales en \"Little Busters! Ecstasy\" son 3 rutas de heroína con los personajes Futaki Kanata, Sasasegawa Sasami y Tokido Saya. Los episodios se incluirán en los lanzamientos de BD / DVD de Little Busters !: Refrain.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/20481.jpg', '2014-01-29'),
(67, 'Mahoutsukai no Yome: Hoshi Matsu Hito ', 3, 'OVA', 'La serie de tres partes de OVA hará una crónica de una historia que tendrá lugar antes de que Chise se encuentre con el Mago.\r\nChise Hatori ha vivido una vida llena de abandono y abuso, sin nada que se parezca al amor. Lejos de la calidez de la familia, ha tenido sus problemas y dificultades. Justo cuando toda esperanza parece perdida, un fatídico encuentro la espera. Cuando un hombre con la cabeza de una bestia, que ejerce extraños poderes, la obtiene a través de una subasta de esclavos, la vida de Chise nunca volverá a ser la misma.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21688-0yOHDBnK3eOu.jpg', '2016-08-13'),
(68, 'Persona 5 The Animation: The Day Breakers ', 1, 'OVA', 'La historia se centra en el Protagonista de 16 años de edad, luego de que lo transfirieron a Shujin High School en Tokio. Al quedarse con los amigos de sus padres, se encuentra con otros dos estudiantes, el niño problemático Ryuuji Sakamoto y Ann Takamaki, y una criatura parecida a un gato que habla y cambia de forma conocida como Morgana. Durante su tiempo allí, sintiéndose reprimido por su entorno, los cuatro forman un grupo conocido como los \"ladrones fantasma\", que trabajan juntos para llevar a cabo atracos y se encuentran con fenómenos misteriosos en el camino.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21432-Cedi86Cv5hOS.jpg', '2016-09-03'),
(69, 'Persona 5 The Animation: Dark Sun.', 1, 'OVA', 'Desenlace de la saga de Akechi Goro.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/n106169-EXFg8nPLs8yb.jpg', '2018-12-31'),
(70, 'Persona 5 the Animation: Stars and Ours ', 1, 'OVA', 'Segunda temporada de Persona 5, el especial de televisión de animación.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx99693-aSdObZr9eBC4.jpg', '2019-03-23'),
(71, 'Shijou Saikyou no Deshi Kenichi', 11, 'OVA', 'OVAs del discípulo más fuerte de la historia de Kenichi incluye los volúmenes 46, 47, 49, 53, 54, 55 y 56 del manga.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/11813.jpg', '2012-03-15'),
(74, 'Tsubasa: Tokyo Revelations', 3, 'OVA', 'Continuando su viaje desde Record Country (el lugar donde se guardaba el libro de los recuerdos), Syaoran y compañía aterrizan en Tokyo Country, un país lleno de sangre en guerra de facciones opuestas por los recursos naturales y la supervivencia. Mientras se involucran a regañadientes en la carrera por vivir, el grupo enfrenta sus propios problemas a medida que se hacen ciertas revelaciones, cambiando su viaje para siempre.\r\nUna traición impactante y una batalla que arriesga toda su vida. Después de esta revelación, nunca volverán a ser los mismos.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/2685.jpg', '2007-11-16'),
(75, 'Mirai Nikki Redial', 1, 'OVA', 'Un añadido del nuevo volumen de manga Future Diary Redial (Mirai Nikki Redial).', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/16762.jpg', '2013-01-19'),
(76, 'Tales of Symphonia The Animation: Sylvarant-hen', 4, 'OVA', 'Existen dos mundos, ambos inconscientes de la existencia del otro. Para que un mundo florezca, el otro tendrá que perecer. En el mundo que perece, un Elegido es enviado a un viaje para restaurar el maná de ese mundo al despertar a los Espíritus y convertirse en un ángel. Colette Brunel, la Elegida de Sylvarant, emprende su viaje acompañada por sus mejores amigos Lloyd Irving y Genis Sage. A medida que viajan más lejos, se encuentran con más amigos e incluso más enemigos, mientras aprenden más y más sobre la verdad detrás de la Regeneración Mundial.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1731-oFymAIpGlDZ9.png', '2007-12-21'),
(77, 'Tales of Symphonia The Animation: Tethe\'alla-hen', 4, 'OVA', 'El segundo arco de Tales of Symphonia que tiene lugar en el floreciente mundo de Tethe\'alla. Esta OVA se lleva a cabo hasta dos tercios del juego, antes del arco Derris-Kharlan.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/5306.jpg', '2010-03-25'),
(78, 'JoJo no Kimyou na Bouken', 6, 'OVA', 'Kujo Jotaro es un estudiante japonés popular, hasta que piensa que está poseído por un espíritu y se encierra en la cárcel. Después de ver a su abuelo, Joseph Joestar, y al luchar contra el amigo de Joseph, Muhammad Abdul, Jotaro se da cuenta de que el \"Espíritu\" es en realidad Star Platinum, su Stand, o energía de combate dado una forma semisólida. Más tarde, su madre gana un puesto, y poco después se enferma. Jotaro se entera de que es porque el vampiro Dio Brando ha revivido 100 años después de su derrota ante Jonathan Joestar, el tatarabuelo de Jotaro. Jotaro decide unirse a Joseph y Abdul en un viaje a Egipto para derrotar a Dio de una vez por todas.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx666-eq1wmsKWQfx7.jpg', '1993-11-19'),
(79, 'Saint Seiya: The Lost Canvas - Meiou Shinwa', 15, 'OVA', 'Una guerra santa, desde la mitología antigua, donde la diosa Atenea y Hades han luchado unos contra otros mientras defendían la tierra repetidamente en el lapso de 200 años. La historia tiene lugar en el siglo XVIII en Europa, 243 años antes del \"Saint Seiya\" original. Tres niños pequeños, Tenma, Alone y Sasha han compartido juntos una infancia muy feliz. Tenma, que es bastante agresiva pero sobresaliente, se ha mudado a Santuario para convertirse en santa. Es allí donde se reúne con Sasha, que es la hermana de Alone y se entera de que ella es la reencarnación de la diosa Atenea. Solo, que es amable, gentil y ama la pintura, fue elegido para el cuerpo del enemigo Rey Hades. Tenma eventualmente se convierte en un santo de Pegasus y se involucra en una feroz batalla con su mejor amigo, Alone, el Rey de Hades. Pegasus Tenma, el rey Hades y la diosa Atenea y, a través del giro de sus 3 destinos, se fusionan para desarrollar un prólogo del original Saint Seiya.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/6171.jpg', '2009-06-14'),
(80, 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2', 13, 'OVA', 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/9130.jpg', '2011-02-23'),
(81, 'Strike The Blood II', 8, 'OVA', 'La segunda temporada de Strike The Blood ', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21815-izZOvSInCptN.jpg', '2016-11-23'),
(82, 'Strike The Blood III', 10, 'OVA', 'La tercera temporada de Strike The Blood', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/n102436-gAWSXDIRWTFK.png', '2018-12-19'),
(83, 'Strike The Blood ', 24, 'Serie', 'El cuarto primogenitor: es el vampiro más fuerte del mundo que solo debería existir en las leyendas. Acompañado por doce Kenjuu y propagación de la calamidad, este vampiro fantasma apareció en Japón. Para la observación y destrucción de este Cuarto Primogenitor, el gobierno y el Rey León decidieron enviar un mago de ataque conocido como Espada Chamán. Sin embargo, por alguna razón, la elegida para la observación fue una aprendiz de la niña Swaman Chamán, Himegari Yukina. Blandiendo la lanza de espíritu anti-primogenitor más fuerte, Yukina llegó al distrito de Demon, en la ciudad de Itogami. ¿Cuál es la verdadera identidad del Cuarto Primogenitor, Akatsuki Kojou, que se encontró allí?', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/18277.jpg', '2013-10-04'),
(84, 'Saiyuki Gaiden', 3, 'OVA', 'Una adaptación en forma de OVA de la cinemática de Saiyuki Gaiden.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/9088.jpg', '2013-03-23'),
(85, 'Death Note', 37, 'Serie', 'Light Yagami es un brillante estudiante de 17 años, uno de los mejores anotadores en sus exámenes en todo Japón. Un día, cuando sale de la escuela, encuentra un misterioso cuaderno negro en el suelo con \"Death Note\" escrito en él. Lo primero escrito en el interior: \"El humano cuyo nombre está escrito en el cuaderno morirá\". Light decide usar esto para limpiar el mundo del mal matando a todos los criminales. En la escena aparece L, un detective, que está decidido a encontrar a Light, a quien el mundo ahora llama \"Kira\", y a rastrearlo, lo que nos brinda una aventura épica y psicológica.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx1535-0seL81FuzaJL.jpg', '2006-10-04'),
(86, 'Ranma 1/2', 161, 'Serie', 'Ranma Saotome y su padre, Genma, ambos practicantes de la escuela Saotome de artes marciales, caen en los manantiales malditos del legendario campo de entrenamiento de Jusenkyo en China continental durante una misión de entrenamiento. Cada primavera tiene una maldición diferente para cualquiera que entre en contacto con su agua, todo lo cual involucra a quién o qué se ha ahogado en la primavera en el pasado: Ranma emerge de la primavera una niña y Genma una panda, ambas ahora malditas para cambiar de forma. Cada vez entran en contacto con agua fría y caliente.\r\n\r\nAl final de su misión de entrenamiento, Genma decide residir con su antiguo compañero de entrenamiento, Soun Tendo, propietario del dojo Tendo y director de la escuela de artes marciales Tendo de todo, va arrastrando a un Ranma reacio junto con él. Soun y Genma discuten los arreglos que habían hecho en el pasado para que Ranma se comprometiera con una de las tres hijas de Soun para combinar las dos escuelas y permitir que Ranma heredara el dojo de Tendo. Se ha decidido de manera informal que debe estar comprometido con Akane Tendo, la hija menor de Soun, y las dos deben aguantarse la una a la otra, y su compromiso, mientras Ranma y su padre se instalan en la vida doméstica en la casa de Tendo.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/210.jpg', '1989-04-15');
INSERT INTO `anime` (`idAni`, `name`, `episode`, `category`, `description`, `cover`, `start_date`) VALUES
(87, 'BoBoBo', 76, 'Serie', 'Bo Bobo es un hombre con el increíble poder de escuchar las voces del cabello y usar el suyo para luchar. Utiliza su poder para luchar contra el Imperio de Margarita y todos los secuaces del Emperador Tsuruui, que se están robando el pelo a cualquiera que encuentren para fortalecer a su emperador.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1050.jpg', '2003-11-08'),
(88, 'Yu-Gi-Oh!', 27, 'Serie', 'Yuugi es un joven un tanto frágil que resulta ser un gran fanático de los juegos de cualquier tipo. Pero cuando resuelve un antiguo rompecabezas egipcio, se le otorgan todos los poderes de la oscuridad. Ahora, cuando se enfrenta con el peligro y la injusticia, se transforma en una forma mucho más oscura y peligrosa, y procede a repartir la justicia y el castigo para aquellos que tanto lo merecen.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/550.jpg', '1998-04-04'),
(89, 'Yu-Gi-Oh! (1999)', 1, 'Película', '\"El Dragón Blanco de Ojos Azules traerá la victoria\", mientras que \"El Dragón Negro de Ojos Rojos traerá el potencial de la victoria\". Un tímido duelista se topa con el legendario Dragón Negro de Ojos Rojos, con esa carta en su poder, debe aprender a mostrar su confianza en el duelo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/2006.jpg', '1999-03-06'),
(90, 'Yu-Gi-Oh! Duel Monsters', 224, 'Serie', 'Yu-Gi-Oh! Duel Monsters se centra en el viaje del espíritu de un antiguo faraón egipcio que intenta volver a descubrir quién era hace muchos años, ya que perdió sus recuerdos. Con la ayuda de un niño, Yugi Mutou, el que despertó el espíritu, y sus amigos, lucha contra muchos villanos y adversarios. Muchos de los villanos han sido vinculados al pasado del Faraón Sin Nombre, debido al Rompecabezas del Milenio que tiene y muchos intentan quitarle el rompecabezas y su poder.\r\nLa serie se centra en el aspecto del juego de cartas y el tema principal representado en toda la serie es la amistad.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/481.jpg', '2000-04-18'),
(91, 'One Punch Man: Road to Hero', 1, 'OVA', 'OVA incluida como el décimo volumen del manga One Punch Man. Presenta una historia original de la serie \'mangaka, ONE, sobre la historia secreta del nacimiento del traje de héroe de Saitama.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/21386-IhO2wnRsZHav.png', '2015-12-04'),
(92, 'Chuunibyou demo Koi ga Shitai!: Kirameki no… Slapstick Noel', 1, 'OVA', 'Episodio 13, incluido en el volumen final del BD / DVD.\r\nDespués de los eventos de \"Chuunibyou demo Koi ga Shitai!\", Se acerca la Navidad y Nibutani le dice a Rikka que esta es una oportunidad para que ella se acerque más a Yuuta. Bajo la sugerencia de Makoto, planean una fiesta de Navidad en la Mansión de Sanae.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/16934.jpg', '2013-06-19'),
(93, 'Net-juu no Susume', 1, 'OVA', 'Episodio 11 de la serie de televisión que no está emitido y que se incluye en el Blu-ray.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx100684-dTFSHninTMEg.jpg', '2017-12-08'),
(94, 'Meitantei Conan OVA 01: Conan VS KID VS Yaiba', 1, 'OVA', 'Conan toma prestada una gran cantidad de manga de Mitsuhiko y comienzan a suceder locuras en la ciudad de Beika. Las cosas no siempre son lo que parecen ser. Una familia le pide a Kogoro que los ayude a proteger una espada especial en su dojo, ya que Kaitou KID le ha dicho que se la va a robar. Sin embargo, Kaitou KID tendrá que robar la espada mientras Conan y Yaiba lo persiguen.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1369.jpg', '2000-05-01'),
(95, 'Meitantei Conan OVA 02: 16 Nin no Yougisha', 1, 'OVA', 'Toda la pandilla es invitada a la villa del inspector Shiratori, donde guarda su colección de vinos, para celebrar su finalización.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/2512.jpg', '2002-05-01'),
(96, 'Meitantei Conan OVA 03: Conan to Heiji to Kieta Shounen', 1, 'OVA', 'Conan y Ran están visitando a Heiji y Kazuha en Osaka, pero mientras están de gira se encuentran con un grupo de tres niños que se parecen a Ayumi, Mitsuhiko y Genta. El grupo está buscando a su amigo desaparecido y Conan acepta ayudarlo.', 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/2513.jpg', '2003-05-01');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `comentario_anime`
--

CREATE TABLE `comentario_anime` (
  `idCom` int(11) NOT NULL,
  `idAni` int(11) NOT NULL,
  `idUsu` int(11) NOT NULL,
  `commentary` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `comentario_anime`
--

INSERT INTO `comentario_anime` (`idCom`, `idAni`, `idUsu`, `commentary`) VALUES
(1, 57, 2, 'Pedazo de Ova\r\n'),
(2, 57, 2, 'Obra Maestra');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `comentario_manga`
--

CREATE TABLE `comentario_manga` (
  `idComman` int(11) NOT NULL,
  `idMan` int(11) NOT NULL,
  `idUsu` int(11) NOT NULL,
  `commentary` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `listamanga`
--

CREATE TABLE `listamanga` (
  `idUsu` int(11) NOT NULL,
  `idMan` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `listanime`
--

CREATE TABLE `listanime` (
  `idUsu` int(11) NOT NULL,
  `idAni` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `listanime`
--

INSERT INTO `listanime` (`idUsu`, `idAni`) VALUES
(2, 3),
(2, 57);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `manga`
--

CREATE TABLE `manga` (
  `idMan` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `episode` int(11) NOT NULL,
  `description` text NOT NULL,
  `cover` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `manga`
--

INSERT INTO `manga` (`idMan`, `title`, `episode`, `description`, `cover`) VALUES
(1, 'Beelzebub', 250, 'La historia sigue al \"delincuente juvenil más fuerte\", Oga Tatsumi, un primer año en \"Ishiyama High\", la escuela para delincuentes. Un día, mientras duerme al lado de un río, ve a un hombre flotando, lo arrastra hasta la orilla y el hombre se divide por la mitad, revelando a un bebé. Este niño es el hijo del demonio rey y ha sido elegido para criarlo con la sirvienta del demonio del bebé Hilda.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx40010-Szo3Nu7Y0wKj.png'),
(2, 'Naruto', 700, 'Antes del nacimiento de Naruto, un gran zorro demonio había atacado la villa oculta de las Hojas. Un hombre conocido como el 4º Hokage, selló al demonio dentro del recién nacido Naruto, lo que hizo que, sin saberlo, creciera detestado por sus compañeros aldeanos. A pesar de su falta de talento en muchas áreas del ninjitsu, Naruto se esfuerza por lograr un solo objetivo: obtener el título de Hokage, el ninja más fuerte de su aldea. Deseando el respeto que nunca recibió, Naruto trabaja por su sueño con sus amigos Sasuke y Sakura, y su maestro Kakashi, mientras pasan por muchas pruebas y batallas para convertirse en un gran ninja y, por tanto, en un gran maestro-', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx30011-9yUF1dXWgDOx.jpg'),
(3, 'Fairy Tail', 545, 'Ambientada en un mundo imaginario,Earth Land, existe un Gremio de Magos llamado \"Fairy Tail\". \r\nFairy Tail está estacionada en la ciudad de Magnolia, que reside en el Reino de Fiore, y actualmente está gobernada por Makarov, el maestro del Gremio.\r\n\r\nLucy Heartfilia, una niña de 17 años, desea convertirse en una maga de pleno derecho y unirse a uno de los gremios de magos más prestigiosos del mundo, Fairy Tail.\r\n\r\nUn día, por pura coincidencia, conoce a Natsu Dragneel, un niño que se pone enfermo cuando viaja, pero de naturaleza muy alegre. Sin embargo, lo que ella no sabe es que Natsu es la conexión más cercana a Fairy Tail, ya que él es mago de este gremio.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/598-4gzaRQ0wHT67.jpg'),
(4, 'Dragon Ball', 520, 'Dragon Ball nos narra las aventuras de Son Goku desde su infancia hasta la edad adulta mientras se entrena en aprender artes marciales y explora el mundo en busca de las siete bolas de dragón conocidas como Dragon Balls, que pueden invocar a un dragón que concede deseos. A lo largo de su viaje, Goku hace varios amigos y lucha contra una gran variedad de villanos, muchos de los cuales también buscan las Bolas de Dragón. En el camino para convertirse en el guerrero más fuerte del universo.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx30042-JvagtyabmZby.png'),
(5, 'Bleach', 686, 'Ichigo Kurosaki siempre ha podido ver fantasmas, pero esta habilidad no cambia su vida tanto como su encuentro cercano con Rukia Kuchiki, una Shinigami y miembro de la misteriosa Sociedad de Almas. Mientras lucha contra un Hollow, un espíritu maligno que se aprovecha de los humanos que muestran energía psíquica, Rukia intenta prestar a Ichigo algunos de sus poderes para que pueda salvar a su familia; Pero para su sorpresa, Ichigo absorbe cada gota de su energía. Ahora que es un Shinigami de pleno derecho, Ichigo se entera rápidamente de que el mundo en el que vive está lleno de espíritus peligrosos y, junto con Rukia, que está recuperando sus poderes lentamente, por tanto, es el trabajo de Ichigo proteger a los inocentes de los Hollows y ayudar a los espíritus a encontrar la paz.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/12-UvTZ3kLjNVAV.png'),
(6, 'Fruits Baskets', 136, 'Tohru Honda es un estudiante de primer año de la escuela de secundaria que está teniendo una seria desgracia. Recientemente no solo quedó huérfana con la tragedia de la muerte de su madre, sino que tampoco tiene dónde vivir, ¡y actualmente reside en una tienda de campaña! Sin embargo, cuando su suerte parece estar en su peor momento, conoce a la familia de Sohma y es invitada a quedarse con ellos a cambio de cuidar las tareas domésticas.\r\n\r\nPero no pasa mucho tiempo antes de que Tohru descubra que los Sohmas tienen un secreto profundo. Los espíritus del zodiaco chino maldicen a la familia, y algunos de los niños nacidos en la familia Sohma pueden ser poseídos por estos espíritus. Cuando están poseídos, no pueden ser \"abrazados\" por el sexo opuesto, ¡o se transforman en su respectivo animal del zodiaco!\r\n\r\nSin embargo, esto no afecta a Tohru, quien promete mantener su secreto. Ella continúa viviendo con ellos, y su grave humildad y agradecimiento nunca se desvanecen. Como resultado, llegan a ser personas muy importantes en su vida, y los Sohmas comienzan a darse cuenta de la suerte que tienen de tenerla.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/102-Zj4EtONCB4KF.png'),
(7, 'Fullmetal Alchemist', 116, 'En este mundo, los alquimistas son aquellos que estudian y realizan el arte de la transmutación alquímica, la ciencia de manipular y transformar la materia. Están limitados por la Ley de Intercambio Equivalente: para obtener algo, uno debe sacrificar algo de igual valor.\r\n\r\nEl joven Edward Elric, apodado \"Alquimista de metal\", es un alquimista estatal que trabaja para el gobierno de Amestris. Cuando era niño, Edward y su hermano pequeño Alphonse intentaron el arte prohibido de la transmutación humana para revivir a su difunta madre. En el accidente que siguió, Edward perdió su pierna izquierda y su brazo derecho, y el alma de Alphonse quedó sellada con una gran armadura. Para reclamar sus cuerpos originales, los hermanos Elric se embarcan en un viaje para encontrar la Piedra Filosofal, un objeto mítico que se dice que permite a su usuario realizar milagros alquímicos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/25-imy9GeynfS89.jpg'),
(8, 'GE: Good Ending', 159, 'Como consecuencia de una respuesta contundente a la que se produjo en el 2009, una toma del mismo título, GE: Good Ending sigue las interacciones del personaje principal Utsuki con Kurokawa Yuki, miembro del equipo de tenis de la escuela, para que Utsuki confiese sus sentimientos. El capitán del equipo de tenis. Se implica que el título del manga se deriva de los \"buenos finales\" que se logran en las novelas visuales de Harem. Aunque la historia una vez se concluyó en la versión de un disparo, la versión completa incluye personajes y configuraciones idénticos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/15578.jpg'),
(9, 'Kami nomi zo Shiru Sekai ', 271, 'Katsuragi Keima es conocido en la red como el dios de conseguir a las chicas, mientras que en la vida real se lo conoce como Otamegane y odia a todas las chicas reales. Sin embargo, es abordado por Elsie, un demonio del infierno, para ayudarla a atrapar espíritus fugitivos que se esconden en las personas. Aparentemente, los espíritus solo se esconden en los corazones de las niñas y la única forma de sacar a las almas es haciendo que la niña se enamore para que el espíritu se vea forzado a salir. Y no se le permite fallar o perderá la cabeza.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/7519-lfuAvV3MeNDl.jpg'),
(10, 'Katekyo Hitman Reborn! ', 411, 'Sawada Tsunayoshi es un chico normal que nunca se ha destacado en los deportes, la escuela o la vida social, por lo que se llama \"No es un buen Tsuna\". Todos los días, él lleva una vida normal, viviendo con su madre, mientras su padre está fuera por trabajo. Pero lo que Tsunayoshi no sabe es que su familia es el linaje real del gran Jefe de la Mafia, el primer jefe de Vongola, Giotto.\r\n\r\nDebido a la historia de Sawada, Tsuna ha sido elegida para convertirse en el décimo jefe de la familia Vongola, una infame familia de la mafia italiana que gobierna el mundo de la Mafia. Para hacerse merecedor del título, Tsuna está siendo ayudado por un sicario y un infante profesional, Reborn, que asume el papel de tutor de la mafia de Tsunayoshi.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/47-Oa1vTAlLi46a.jpg'),
(11, 'Shijou Saikyou no Deshi Kenichi', 584, 'La historia está centrada en Kenichi Shirahama, un chico debilucho promedio de 15 años, cuya vida se convierte en el infierno con la aparición de la ingenua, hermosa y fuerte estudiante transferida, Miu Fūrinji. Después de que Kenichi es testigo de las habilidades de Miu en las artes marciales, se une al dojo Ryōzanpaku, el lugar de reunión de aquellos que son verdaderamente fuertes, que también es la casa de Miu. Después de vencer a un estudiante de karate en un partido, pronto es atacado por todos los delincuentes en la escuela. Desde entonces, la rutina de Kenichi se divide entre su entrenamiento infernal con los maestros de Ryōzanpaku y sus luchas contra los miembros de Ragnarok, una pandilla que lo ve como un posible aliado o una amenaza inminente para sus planes.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/988-lgP8ihiu361X.jpg'),
(12, 'Magi: The Labyrinth of Magic ', 369, 'Esta historia trata sobre el flujo del destino y la batalla para mantener al mundo en el camino correcto. Aladdin es un niño que se ha propuesto explorar el mundo después de haber estado atrapado en una habitación durante la mayor parte de su vida. Su mejor amigo es una flauta con un genio llamado Ugo. Muy pronto, Aladdin descubre que él es un Magi, un mago que elige a los reyes, y nació para elegir a los reyes que seguirán el camino del justo, luchando contra aquellos que quieren destruir el destino. Sigue sus aventuras mientras se encuentra con otros de \"One Thousand and One Nights\", como Ali Baba y Sinbad, y lucha para mantener el equilibrio del mundo bajo control.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/14790-Gep4QAni2F9Z.jpg'),
(13, 'Magi: Sinbad no Bouken ', 182, 'Un prólogo de la serie de manga que cuenta la historia de los primeros años de vida de Sinbad.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx78025-mG6hLLMEZGNa.jpg'),
(14, 'Masamune-kun no Revenge ', 49, 'Masamune ha cambiado mucho por una sola razón: quiere venganza. Contrariamente a su pasado, ha trabajado duro para ser guapo con el fin de lograr este objetivo. Más rápido de lo previsto, incluso cumple con el objetivo de su venganza el primer día después de la transferencia en - Adagaki Aki. No pierde el tiempo en comenzar su plan, pero la venganza no es fácil.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/46716-0I8UN64G8bnS.jpg'),
(15, 'Nisekoi', 229, 'Cuando era niño, Raku Ichijo hizo una promesa secreta con su novia de la infancia, manteniendo un colgante como recuerdo mientras su amor se llevó la llave. Sueña con un día conocer a su amor pasado, pero años más tarde, la realidad rompe sus esperanzas cuando Chitoge Kirisaki lo arrodilla por casualidad ...\r\n\r\nAunque Raku es un estudiante normal de secundaria, su familia encabeza la notoria pandilla yakuza de la facción Shuei-Gumi. ¡Y es arrastrado a los asuntos familiares cuando se ve forzado a tener una relación con Chitoge, la hija del jefe de una pandilla rival!\r\n\r\nA pesar de sus continuas discusiones, los dos de alguna manera engañan a todos con su falsa relación. Raku luego descubre que Chitoge tiene una clave misteriosa de su pasado, que ella no puede recordar ... Además, otras dos chicas también aparecen con llaves: ¡Kosaki Onodera y Marika Tachibana!\r\n\r\nAtrapado en medio de esta vorágine de amor, surgen aún más complicaciones para Raku cuando su clase decide sobre Romeo y Julieta como el juego de la clase para el festival escolar. ¿Pueden los dos enamorados falsos lograr lo imposible y hacer que el juego sea un éxito?', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/31499.jpg'),
(16, 'ReLife', 222, 'La historia sigue a Kaizaki Arata, un joven desempleado de 27 años, que fracasa en todas las entrevistas de trabajo que tuvo después de abandonar su última empresa. Su vida cambia después de conocer a Yoake Ryou del ReLife Research Institute, quien le ofreció un medicamento que puede cambiar su apariencia a 17 años y convertirse en un sujeto en un experimento durante un año. Así, comienza una vez más su vida como estudiante de secundaria.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx85849-TYAa7nhwSvbx.jpg'),
(17, 'Shaman King', 285, 'Yoh Asakura es un chamán, uno de los pocos talentosos que, gracias al entrenamiento o al talento natural, puede canalizar espíritus que la mayoría de las personas ni siquiera pueden ver. Con la ayuda de su prometida, Anna, Yoh está entrenando para el último evento deportivo de chamanes: la \"Pelea de chamanes en Tokio\", el torneo de una vez cada 500 años para ver quién puede dar forma al futuro de la humanidad y convertirse en el Rey de los chamanes. Pero desafortunadamente para Yoh, todos los chamanes del mundo compiten por el mismo premio ...\r\n\r\nEl último single-shot serializado, Mappa Douji, Relax y el manga corta, Funbari no Uta también se incluyen en los volúmenes de Shaman King.\r\n\r\nLa historia paralela Funbari no Uta, que dura cinco capítulos, se desarrolla siete años después del final de la serie de manga y presenta a Hana Asakura y su viaje con su tío Ryu para reunir a los 5 guerreros elementales.\r\n\r\nLa historia paralela Mappa-Douji muestra la infancia de Hao en su vida original. Sigue la historia de Hao en el Japón feudal a través de la muerte de su madre a manos de los humanos, conociendo a su primer amigo espiritual y desarrollando sus poderes de lectura mental y otras habilidades chamánicas avanzadas. La historia lateral Relax sigue a Hao reuniendo seguidores para los años del torneo antes de que comenzara.\r\n\r\n', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx42917-D9bqCBW70vN5.png'),
(18, 'Tokyo Ghoul', 144, 'Shy Ken Kaneki está encantado de ir a una cita con la hermosa Rize. Pero resulta que a ella solo le interesa su cuerpo, comerlo, es decir. Cuando un rescate moralmente cuestionable lo transforma en el primer híbrido semihumano mitad humano, Ken se ve arrastrado al oscuro y violento mundo de los Ghouls, que existe junto al nuestro.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx63327-VpmcwQGbXZh5.jpg'),
(19, 'Tokyo Ghoul Re', 179, 'En Tokio, una desesperación inmutable está al acecho. Misteriosos seres devoradores de hombres, demonios, corren desenfrenados en Tokio. Viviendo oculto durante la vida cotidiana, la existencia de los ghouls, cuyas verdaderas identidades están envueltas en un misterio, aterroriza permanentemente a los residentes de Tokio.\r\n\r\nEn CCG, la única institución que investiga y resuelve los casos relacionados con los ghouls, a Haise Sasaki se le ha asignado una misión determinada. Al tratar con los cuatro niños ingobernables del problema conocidos como \"Quinx\", ¡comienzan los días de sufrimiento de Haise ...?!', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/55611-eAVXqML2ZKj4.jpg'),
(20, 'Ansatsu Kyoushitsu', 187, 'En un abrir y cerrar de ojos, el cielo nocturno cambia para siempre cuando, con una gran explosión, la luna se convierte en un creciente permanente. Enfrentando a los gobiernos del mundo, un monstruo amarillo con tentáculos se jacta de que fue el responsable de la catástrofe, y dentro de un año, hará lo mismo con la Tierra. Mirando a Mach 20, la criatura hace una demanda peculiar: una posición de enseñanza en la prestigiosa escuela secundaria Kunugigaoka. Desesperados por mantener a la criatura en un lugar, el gobierno está de acuerdo, y así los estudiantes de la Clase 3-E se enfrentan a una tarea imposible: asesinar a la criatura responsable de destruir la luna.Aunque el destino del mundo ahora descansa sobre sus hombros, la clase tiene más problemas personales que enfrentar. Atrapados en el fondo del sistema de educación jerárquico de Kunugigaoka, se enfrentan a una dura discriminación tanto de profesores como de estudiantes. Abundan las derrotas, no se creen capaces de triunfar en la vida diaria, y mucho menos en contra de un monstruo que supera las capacidades de cualquier humano. Pero a medida que la enigmática criatura, a la que denominan Koro-sensei, los educa tanto en el asesinato como en la academia, los niños encuentran lentamente el coraje para levantarse y apuntar a su objetivo: el mejor maestro que el mundo haya visto.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx69883-oNQPq5VnuWb8.png'),
(21, 'Digimon Adventure', 35, 'Siete niños disfrutan de sus vacaciones de verano en un campamento, cuando de repente, se ven envueltos en un misterios mundo: El Mundo Digital. Un mundo paralelo al suyo formado a partir de datos digitales. Allí conocen a sus compañeros los digimon, y juntos tendrán que solucionar los extraños sucesos que aterran la Isla File, provocados por Devimon. Pero tal vez no sea esa el único motivo por el que aparecieron en aquél misterioso mundo, tendrán que enfrentarse a más de una aventura para descubrirlo y volver a su mundo.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/b32387-QN70LtQMvzZW.jpg'),
(22, 'Saiyuki Gaiden', 34, '500 años antes de la historia de Saiyuki, un niño herético con ojos dorados es llevado al cielo. Se le entrega al cuidado renuente de una deidad menor llamada Konzen, el sobrino de la Diosa Misericordiosa Kanzeon Bosatsu. Konzen finalmente le da al niño el nombre \"Goku\". Goku se hace amigo de otros dos dioses menores, el Mariscal Tenpou y el General Kenren del Ejército del Cielo Occidental. También conoce a un niño pequeño y extraño que parece tener su propia edad, el Príncipe de Guerra Nataku. Aunque Goku es feliz en su nuevo hogar, Heaven no es amable con los herejes. Hay quienes usarían a Nataku y Goku como herramientas para intentar apoderarse del trono del Cielo, y Konzen, Tenpou y Kenren podrían no ser capaces de salvarlos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/1097.jpg'),
(23, 'Slum Dunk', 276, 'Hanamichi Sakuragi es un delincuente que nunca ha tenido suerte con las chicas. Sin embargo, cuando conoce a Haruko Akagi, está seguro de que ella es la adecuada para él. Haruko es un gran fanático del baloncesto y nota su potencial como jugador de baloncesto (debido a su inmensa altura). Con la esperanza de ganar su corazón, Hanamichi ensaya seriamente para el equipo de baloncesto. ¿Este novato completo tiene lo necesario para unirse al equipo?', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/51-CNwxU6AFbx5z.jpg'),
(24, '20th Century Boys', 249, 'La humanidad, al haberse enfrentado a la extinción a fines del siglo XX, no habría entrado en el nuevo milenio si no hubiera sido por ellos. En 1969, durante su juventud, crearon un símbolo. En 1997, a medida que el desastre venidero comienza a desarrollarse lentamente, ese símbolo regresa. Esta es la historia de un grupo de niños que intentan salvar el mundo.\r\n\r\nPara Kenji, un simple gerente de una tienda de conveniencia que una vez soñó con convertirse en un músico de rock \'n\' roll, una gran cantidad de recuerdos de su pasado vuelven rápidamente cuando uno de sus amigos de la infancia se suicida misteriosamente. ¿Podría esta nueva muerte estar relacionada con el surgimiento de un nuevo y extraño culto que ha sido implicado en varios otros asesinatos y desapariciones? Determinado a profundizar, Kenji se reúne con algunos de sus viejos amigos con la esperanza de aprender la verdad detrás de todo esto.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/3-gmYZVYVvAzKI.jpg'),
(25, 'Pluto', 65, 'Basado en un arco de la historia de Tesuwan Atomu de Osamu Tezuka, Pluto sigue al detective de Europol Gesicht mientras intenta descubrir el misterio detrás de una cadena de robots y muertes humanas. El caso se vuelve mucho más desconcertante cuando la evidencia se inclina hacia los asesinatos que son el trabajo de un robot, que es algo que no ha ocurrido en 8 años.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/n30745-OtSJxYzzvz2X.png'),
(26, 'Death Note', 108, 'Light Yagami es un brillante estudiante de 17 años, uno de los mejores anotadores en sus exámenes en todo Japón. Un día, cuando sale de la escuela, encuentra un misterioso cuaderno negro en el suelo con \"Death Note\" escrito en él. Lo primero escrito en el interior: \"El humano cuyo nombre está escrito en el cuaderno morirá\". Light decide usar esto para limpiar el mundo del mal matando a todos los criminales. En la escena aparece L, un detective, que está decidido a encontrar a Light, a quien el mundo ahora llama \"Kira\", y a rastrearlo, lo que nos brinda una aventura épica y psicológica.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx30021-qfGufBWpSX1z.jpg'),
(27, 'Cardcaptor Sakura', 50, 'Un día, Sakura Kinomoto abrió accidentalmente un libro que contenía docenas de cartas mágicas llamadas Clow Cards, y se dispersaron alrededor de su ciudad natal, Tomoeda. Sakura fue elegida para ser la dueña de estas cartas y el guardián Kerberos, alistado en el sol, se alistó para usar su magia y reclamar estas cartas antes de que causen más problemas en la ciudad. Ella es alentada por su mejor amigo Tomoyo Daidouji, y conoce a un rival de la tarjeta, Syaoran Li, quien es un descendiente directo del creador de las Cartas Clow.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/106-eQ9g0cZNQ8ZZ.png'),
(28, 'Kingdom Hearts', 43, 'Sora es un joven enérgico que espera explorar el mundo con sus amigos, Riku y Kairi. El trío está trabajando duro para completar una balsa que les permitirá salir de su isla, pero un día, una fuerza misteriosa hace que Sora obtenga un arma especial conocida como Keyblade. Él lucha contra algunos monstruos extraños y se transporta a una ciudad extraña. Mientras tanto, Donald y Goofy abandonan su castillo para buscar al rey y al elegido que tiene la \"llave\" para salvar al mundo. Sora es atacada nuevamente por criaturas conocidas como Sin corazón, pero recibe ayuda de un anciano llamado Cid y un guerrero llamado León. Finalmente se encuentra con Donald y Goofy y se unen para buscar a sus amigos y al Rey. Versión Cómica del Videojuego Kingdom Hearts.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/396.jpg'),
(29, 'Kingdom Hearts: Chain of Memories', 13, 'La puerta de Kingdom Hearts estaba sellada, asestando un golpe a los despiadados y restaurando los mundos a la normalidad, ¡pero Riku y King Mickey estaban atrapados adentro! Ahora, la búsqueda de Sora, Donald y Goofy de sus amigos los lleva al misterioso Castillo del Olvido, donde una figura encapuchada les dice: \"Por delante hay algo que necesitas, pero para reclamarlo, debes perder algo, cariño\". ¿Qué podría ser más querido que sus propios recuerdos? ¿Y qué quieren los miembros en la sombra de la Organización XIII con ellos? Versión Cómica del Videojuego Kingdom Hearts Chains of Memories', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/397.jpg'),
(30, 'Kingdom Hearts: 358/2 Days', 35, 'Los Sincorazón con ansias de corazones. La rabia de la Llave Espada que desata esos corazones. Los corazones se reúnen en la oscuridad, y eventualmente crea Kingdom Hearts; Para crear el santuario para aquellos corazones perdidos, esos es Kingdom Hearts. Roxas, sin ningún recuerdo de su pasado, ha sido aceptado en la Organización XIII. El privilegio de convertirse en miembro de la Organización XIII viene con la responsabilidad que cada miembro mantiene. Sin embargo, surge una pregunta: \"¿Por qué estoy en la organización?\" En la parte superior de la torre del reloj con la puesta de sol en el horizonte, el miembro número 14, una joven, hace esta pregunta. ¿Quién es esta niña y cómo encaja en la trama? Esta es la revitalización de Kingdom Hearts; La nueva precuela que conecta las piezas del rompecabezas de los misterios que aún flotan. Esto es Kingdom Hearts: 358/2 días! Versión Cómica del Videojuego Kingdom Hearts 358/2 Days.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx45104-zaeEuCksF6xx.jpg'),
(31, 'Kingdom Hearts II', 69, 'En el pequeño y tranquilo mundo de Villa Crepusculo, vive un niño llamado Roxas. Él y sus amigos Hayner, Pence y Olette están tratando de disfrutar sus últimos días de vacaciones de verano, cuando comienzan a suceder cosas extrañas. Primero, acusan falsamente al grupo de robar fotos de toda la ciudad. Luego son atacados por extrañas criaturas blancas. Pero los acontecimientos más extraños son los sueños recurrentes que Roxas tiene sobre un niño llamado Sora y la presencia de una niña llamada Naminé, que tiene un secreto misterioso para compartir con Roxas.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/398.jpg'),
(32, 'La Ley de Ueki', 154, 'La Ley de Ueki cuenta la historia sobre la Batalla de unos Poderes Sobrenaturales, un torneo para decidir quién será el próximo Rey del Mundo Celestial. Se requiere que cada candidato (100 en total) elija a un estudiante de secundaria para que actúe como su luchador. Cada estudiante recibe un poder único: el poder de cambiar una cosa por otra. El Rey ganador del Mundo Celestial Candidato se convertirá en el Rey del Mundo Celestial y el estudiante ganador recibirá el Talento en blanco (zai en blanco), un talento que puede ser cualquier cosa que elijan.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/326.jpg'),
(33, 'La Ley de Ueki Plus', 46, 'Dos años después del torneo del próximo dios, Kosuke Ueki es ahora un estudiante de tercer año en la Escuela Secundaria Hinokuni. Por alguna razón, todos en el mundo real han perdido la memoria de su persona más importante, incluidos sus amigos, que participaron en el torneo hace dos años. Ueki, al ser la única persona que queda afectada en el mundo, está luchando para restaurar los recuerdos de todos. Ueki sigue una pequeña oveja llamada U-lu a otro mundo llamado Hankagai. Allí, se encuentra con nuevos compañeros y gana nuevos poderes.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/327.jpg'),
(34, 'Pandora Hearts', 107, 'El aire de celebración que rodea a la ceremonia de la mayoría de edad de Oz Vessalius, de 15 años, se convierte rápidamente en horror cuando es condenado por un pecado del cual no sabe nada. Él es arrojado a una prisión eterna e ineludible conocida como el Abismo del cual no hay escapatoria. Allí conoce a una joven llamada Alice, que no es lo que parece. Ahora que los implacables engranajes del destino han comenzado a girar, ¿conducen solo a la desesperación aplastante de Oz, o hay un poco de esperanza para que él los alcance?', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx33031-rR2oeXP6HdPi.jpg'),
(35, 'School Rumble', 345, 'La estudiante de segundo año Tsukamoto Tenma se entera de que su enamoramiento secreto, Karasuma Oji, será transferido a una escuela en Estados Unidos. En un último esfuerzo por revelarle su amor, ella escribe una larga (pero anónima) carta de amor. Cuando Karasuma termina posponiendo su transferencia por un año más, Tenma se da cuenta de que tiene que decirle cómo se siente antes de que se agote el tiempo. Pero su extremo nerviosismo a su alrededor la impulsa a intentar configurar todo tipo de esquemas para acercarse a él y hacerle saber, sin realmente salir y decirlo. Mientras tanto, desconocida para Tenma, la delincuente de la escuela, Harima Kenji, está más enamorada de ella, así como las mismas inquietudes de ser directos. Alrededor de este triángulo amoroso de personas despistadas se encuentran algunas de las amigas de Tenma, y su hermana más joven (pero de aspecto mayor, más madura y más popular). Este manga consta de 283 capítulos afilados y 62 capítulos planos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/160-GWfClaspYd2r.jpg'),
(36, 'Rurouni Kenshin', 259, 'La historia de Rurouni Kenshin tiene lugar durante el período Meiji temprano en Japón. Cuenta la historia de un vagabundo pacífico llamado Himura Kenshin, anteriormente conocido como el asesino Hitokiri Battōsai. Después de participar en la guerra de Bakumatsu, Kenshin recorre el campo de Japón ofreciendo protección y ayuda a los necesitados como expiación por los asesinatos que una vez cometió como asesino. Al llegar a Tokio, conoce a una joven llamada Kamiya Kaoru, quien se encontraba en medio de una pelea con un asesino que dice ser el Hitokiri Battōsai de su escuela de espada. Kenshin decide ayudarla y derrota al falso Battōsai. Después de descubrir que Kenshin es el verdadero Battōsai, ella le ofrece un lugar para quedarse en su dojo mientras observa que Kenshin es una persona amable en su lugar. Kenshin acepta y comienza a establecer relaciones de por vida con muchas personas, incluidos los ex enemigos, mientras trata con su parte justa de enemigos, nuevos y viejos.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/22-Gb67gI53eafv.jpg'),
(37, 'Bakuman', 176, 'Bakuman sigue la historia de la estudiante de secundaria Moritaka Mashiro, un talentoso artista que no sabe qué quiere hacer con su futuro. Un día, Mashiro dibuja una foto de Miho Azuki, una chica a la que ama secretamente, durante la clase, pero olvida el cuaderno en la escuela. Regresa y descubre que su compañero Akito Takagi lo está esperando con su cuaderno. Takagi trata de convencer a Mashiro de que se convierta en un artista de manga para sus historias, lo que lleva al desacuerdo de Mashiro, y cita a su difunto tío, que murió por exceso de trabajo.\r\n\r\nTakagi incita a Mashiro a reunirse con Miho Azuki, el enamorado de Mashiro, y le dice que los dos planean convertirse en artistas de manga. En respuesta, Azuki revela sus planes para ser una actriz de voz. Mashiro le propone a ambos que se casen cuando Azuki se convierta en una actriz de voz para la adaptación al anime de su manga. Los dos comienzan a crear su manga, bajo el seudónimo de Muto Ashirogi, con la esperanza de ser serializados en Weekly Shounen Jump.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx39711-tjPWXT1AW321.jpg'),
(38, 'Ranma 1/2', 407, 'En China, se encuentra un famoso manantial de entrenamiento, un lugar donde los artistas marciales pueden perfeccionar sus habilidades a grandes niveles. Desafortunadamente, los manantiales también están malditos! El artista marcial adolescente Ranma cae en el \"manantial de la niña ahogada\" y ahora se convierte en mujer cada vez que se salpica con agua fría. Eso no impide que su padre lo involucre con Akane, la hija de un viejo amigo y una niña dura que tiene algo mejor que hacer que preocuparse por los niños. Pero Akane no es la única chica que tiene una oportunidad para los afectos de Ranma, otras dos chicas también han estado comprometidas con él. Pero Ranma tiene mejores cosas que hacer que preocuparse por su vida amorosa, ¡como hacer una plétora de rivales locos y aún más pretendientes!', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx30023-J0a0HrJy8CEb.png'),
(39, 'Soul Eater', 117, 'En un mundo donde los técnicos manejan a los humanos selectos que pueden convertirse en armas, Shinigami-sama creó una escuela para enseñar a los jóvenes técnicos y a sus compañeros que cambian de forma lo que significa ser un dios de la muerte. Para crear el arma definitiva, los estudiantes de la escuela deben recolectar las almas de 99 humanos malvados y 1 bruja.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/908-URcv8ktTOI7S.png'),
(40, 'Bobobo-bo Bo-bobo', 230, 'En el año 300X, la Tierra está aterrorizada por el malvado Imperio Margarita, que no se detendrá ante nada para librar a toda la población de su cabello. Pero ahora, un hombre que lleva el pelo afro se interpone en su camino. Tiene la capacidad de comunicarse con el cabello de otras personas y usar su propio vello nasal para derrotar a los hombres calvos del Imperio Margarita. Su nombre: Bobobo-bo Bo-bobo.\r\n', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/nx31505-WOV9hxugkFnq.jpg'),
(41, 'Bobobo-bo Bo-bobo Shinsetsu ', 74, 'Comenzando un año después de la final de la primera serie, el antiguo emperador Tsuru Tsurulina III reformó el Imperio Margarita para convertirlo en el Imperio Neo-Margarita, donde se reanudan las Caídas del cabello y se crea una nueva generación de poderosos generales. Bo-bobo, potenciando las habilidades de su \"Puño del pelirrojo\" en su forma de \"Verdadera teoría\", se une a Beauty y los aliados de Hajike para asumir la amenaza renovada de Margarita.', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/11210.jpg'),
(42, 'Yu-Gi-Oh!', 343, 'Yugi, de 10º grado, pasó la mayor parte de su tiempo solo jugando juegos, ¡hasta que resolvió el Rompecabezas del Milenio, un misterioso artefacto egipcio! Poseído por el rompecabezas, Yugi se convierte en Yu-Gi-Oh, el Rey de los Juegos, y desafía a los malhechores a los Juegos de la Sombra: ¡juegos extraños con altas apuestas y altos riesgos! ¡Estas novelas gráficas contienen nuevas historias que no se vieron en el anime, incluido el origen de Yugi y sus amigos!\r\n', 'https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/54-jwRYFssmE9lQ.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

CREATE TABLE `users` (
  `idUsu` int(11) NOT NULL,
  `name` varchar(20) NOT NULL,
  `password` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `type` tinyint(1) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`idUsu`, `name`, `password`, `email`, `type`) VALUES
(2, 'Adri', '1234', 'prueba@prueba.com', 1),
(3, 'Kyoya', 'Bankai93', 'adrisanchez39@gmail.com', 1),
(4, 'Admin', 'Admin', 'admin@admin.com', 0);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `anime`
--
ALTER TABLE `anime`
  ADD PRIMARY KEY (`idAni`);

--
-- Indices de la tabla `comentario_anime`
--
ALTER TABLE `comentario_anime`
  ADD PRIMARY KEY (`idCom`);

--
-- Indices de la tabla `comentario_manga`
--
ALTER TABLE `comentario_manga`
  ADD PRIMARY KEY (`idComman`),
  ADD KEY `fk_id_man` (`idMan`),
  ADD KEY `fk_id_usu` (`idUsu`);

--
-- Indices de la tabla `listamanga`
--
ALTER TABLE `listamanga`
  ADD KEY `fk_usu_man` (`idUsu`),
  ADD KEY `fk_man_usu` (`idMan`);

--
-- Indices de la tabla `listanime`
--
ALTER TABLE `listanime`
  ADD KEY `fk_lista` (`idUsu`),
  ADD KEY `fk_anime` (`idAni`);

--
-- Indices de la tabla `manga`
--
ALTER TABLE `manga`
  ADD PRIMARY KEY (`idMan`);

--
-- Indices de la tabla `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`idUsu`),
  ADD UNIQUE KEY `nombre` (`name`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `anime`
--
ALTER TABLE `anime`
  MODIFY `idAni` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=97;

--
-- AUTO_INCREMENT de la tabla `comentario_anime`
--
ALTER TABLE `comentario_anime`
  MODIFY `idCom` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT de la tabla `comentario_manga`
--
ALTER TABLE `comentario_manga`
  MODIFY `idComman` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `manga`
--
ALTER TABLE `manga`
  MODIFY `idMan` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=43;

--
-- AUTO_INCREMENT de la tabla `users`
--
ALTER TABLE `users`
  MODIFY `idUsu` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `comentario_manga`
--
ALTER TABLE `comentario_manga`
  ADD CONSTRAINT `fk_id_man` FOREIGN KEY (`idMan`) REFERENCES `manga` (`idMan`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_id_usu` FOREIGN KEY (`idUsu`) REFERENCES `users` (`idUsu`) ON DELETE CASCADE;

--
-- Filtros para la tabla `listamanga`
--
ALTER TABLE `listamanga`
  ADD CONSTRAINT `fk_man_usu` FOREIGN KEY (`idMan`) REFERENCES `manga` (`idMan`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_usu_man` FOREIGN KEY (`idUsu`) REFERENCES `users` (`idUsu`) ON DELETE CASCADE;

--
-- Filtros para la tabla `listanime`
--
ALTER TABLE `listanime`
  ADD CONSTRAINT `fk_anime` FOREIGN KEY (`idAni`) REFERENCES `anime` (`idAni`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_lista` FOREIGN KEY (`idUsu`) REFERENCES `users` (`idUsu`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
